### ISSUE TITLE
请问我想要更新ffmpeg的版本，应该怎么做

### ISSUE THREAD

**Issue by xiaowu4** [yangjie10930/EpMedia#11]
由于某些原因，需要更新ffmpeg的版本，请问需要怎么做呢？

**Comment by yangjie10930** [comment]
暂时没办法自己更新，等更新新版本吧。

**Comment by yangjie10930** [comment]
@xiaowu4 已更新FFmpeg至3.3.4版本，更新EpMedia至v0.7.1版本

**Comment by xiaowu4** [comment]
@yangjie10930 好的，感谢

**Comment by xiaowu4** [comment]
@yangjie10930  
您好，我在编译ffmpeg的时候遇到了很多问题，请教一下。如果您有时间帮我看一下。
我的编译脚本如下：
#!/bin/bash
export TMPDIR=/home/wushuo/dev/ffmpeg/ffmpeg/tmpdir
NDK=/home/wushuo/dev/ndk/android-ndk-r10e
SYSROOT=$NDK/platforms/android-16/arch-arm
TOOLCHAIN=$NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
CPU=arm
PREFIX=/home/wushuo/dev/ffmpeg/ffmpeg/output/$CPU
ADDI_CFLAGS="-marm -I/home/wushuo/dev/ffmpeg/thirdparty/include"
ADDI_LDFLAGS="-L/home/wushuo/dev/ffmpeg/thirdparty/lib -lmp3lame -lfreetype -lx264 -lfribidi"
function build_one
{
./configure \
--prefix=$PREFIX \
--extra-cflags="$ADDI_CFLAGS" \
--extra-ldflags="$ADDI_LDFLAGS" \
--enable-cross-compile \
--cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- \
--target-os=android \
--arch=armv7-a \
--sysroot=$SYSROOT \
--enable-shared \
--disable-static \
--enable-asm \
--enable-neon \
--enable-jni \
--enable-mediacodec \
--enable-decoder=h264_mediacodec \
--enable-hwaccel=h264_mediacodec \
--disable-doc \
--disable-ffmpeg \
--disable-ffplay \
--disable-ffprobe \
--disable-ffserver \
--disable-avdevice \
--disable-doc \
--disable-symver \
--enable-libx264 \
--enable-libfreetype \
--enable-libfribidi \
--enable-libmp3lame \
--enable-gpl \
--enable-nonfree \
--enable-version3 \
--enable-small \
--disable-vda \
--disable-iconv \
--disable-encoders \
--enable-encoder=libx264 \
--enable-encoder=mpeg4 \
--enable-encoder=aac \
--enable-encoder=gif \
--enable-encoder=libmp3lame \
--disable-muxers \
--enable-muxer=mp4 \
--enable-muxer=gif \
--enable-muxer=aac \
--enable-muxer=mp3 \
--disable-decoders \
$ADDITIONAL_CONFIGURE_FLAG
make clean
make -j8
make install
}
build_one
报如下错误，应该怎么办啊
/home/wushuo/dev/ndk/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc is unable to create an executable file.
**# C compiler test failed.**
