### ISSUE TITLE
添加背景音乐时，出错

### ISSUE THREAD

**Issue by galibujianbusana** [yangjie10930/EpMedia#110]
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@1133f671
versionCode=1
BOARD=SCL-TL00H
BOOTLOADER=unknown
TYPE=user
matchers=[Ljava.lang.String;@39ee24d7
ID=HonorSCL-TL00H
TIME=1479754077000
BRAND=Honor
TAG=Build
SERIAL=JTJ4C15C01008794
HARDWARE=qcom
SUPPORTED_ABIS=[Ljava.lang.String;@349c8c56
CPU_ABI=armeabi-v7a
RADIO=unknown
IS_DEBUGGABLE=false
replacements=[Ljava.lang.String;@ee961c4
MANUFACTURER=HUAWEI
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@1eda9c18
TAGS=release-keys
CPU_ABI2=armeabi
UNKNOWN=unknown
USER=huawei
FINGERPRINT=Honor/SCL-TL00H/hnSCL-Q:5.1.1/HonorSCL-TL00H/C00B262:user/release-keys
HOST=huawei-desktop
PRODUCT=SCL-TL00H
versionName=1.0
DISPLAY=SCL-TL00HC00B262
HIDE_PRODUCT_INFO=false
MODEL=SCL-TL00H
DEVICE=hnSCL-Q
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_rdft_calc" referenced by "libavfilter.so"...
	at java.lang.Runtime.loadLibrary(Runtime.java:383)
	at java.lang.System.loadLibrary(System.java:997)
	at Jni.FFmpegCmd.<clinit>(FFmpegCmd.java:22)
	at Jni.FFmpegCmd.exec(FFmpegCmd.java:73)
	at VideoHandle.EpEditor.execCmd(EpEditor.java:571)
	at VideoHandle.EpEditor.music(EpEditor.java:326)

-----
自己写的一个小demo 添加背景音乐可以正常使用，但是加到另一个项目时，就一直报上面的错误了……

**Comment by yangjie10930** [comment]
检查下添加方法,配置文件jniLibs.srcDirs
