### ISSUE TITLE
关于FFmpeg库疑问

### ISSUE THREAD

**Issue by ruijun** [yangjie10930/EpMedia#117]
@yangjie10930 Hello，该项目是基于https://github.com/Bilibili/FFmpeg 吗？

**Comment by eskyos** [comment]
作者已经提供ffmpeg jni代码

**Comment by ruijun** [comment]
@eskyos 哦，可能是我说得不够清楚。作者提供的jni代码，ffmpeg.c，ffmpeg.h这些也是从FFmpeg库里面抽取出来的。我是想问下是不是用了bilibili修改过的ffmpeg库。

**Comment by yangjie10930** [comment]
@ruijun 不是，官网上下的

**Comment by ruijun** [comment]
@yangjie10930 好的，我看了Android.mk文件 `LOCAL_C_INCLUDES := E:\ijkPlayer\EpMedia\ffmpeg-3.3.4` 我以为是用了bilibili修改过的ffmpeg库。
