### ISSUE TITLE
ffmpeg调用疑问

### ISSUE THREAD

**Issue by qinyang1018** [yangjie10930/EpMedia#118]
用命令调用底层代码和直接调用底层代码的方法封装   是不是第二种的效率更好一些？  对命令调用和封装的方法调用有些疑问  想请教下

**Comment by yangjie10930** [comment]
直接调用底层ffmpeg提供的api拓展性更好，命令只是方便使用，命令也是调用api的。

**Comment by qinyang1018** [comment]
性能上是没有区别的吧？

**Comment by yangjie10930** [comment]
没区别

**Comment by qinyang1018** [comment]
好的 了解了 非常感谢
