### ISSUE TITLE
关于开源jni编译不过的问题

### ISSUE THREAD

**Issue by ethan0913** [yangjie10930/EpMedia#121]
下载了代码和demo的代码。把jni的代码复制过去。编译出现找不到路径的问题。把Android.mk中LOCAL_C_INCLUDES的值修改后编译大部分libavdevice可以找到但是compat还是找不到，libavresample包也没有。是不是jni部分的代码上传缺些东西？

**Comment by ethan0913** [comment]
在android.mk中LOCAL_C_INCLUDES := E:\videoparser\EpMediaDemo\app\src\main\jni\include修改为本地项目路径。
编译报错Error:(34, 10) fatal error: 'compat/va_copy.h' file not found
![default](https://user-images.githubusercontent.com/16099113/39980646-8c4b9e0a-577f-11e8-8757-e20f84299a97.png)

**Comment by eskyos** [comment]
你需要本地有一套ffmpeg的源码，然后让其头文件指到该路径，你需要的头文件就可以识别了。

**Comment by eskyos** [comment]
![image](https://user-images.githubusercontent.com/4328982/40339389-dbd4f3f8-5dac-11e8-9627-98f2c73f9253.png)
