### ISSUE TITLE
添加背景音乐时（mp3）,amix unconnected ，aout is not exist.

### ISSUE THREAD

**Issue by csuZipple** [yangjie10930/EpMedia#125]
错误信息：
1.
E/FFmpeg_EpMedia: Filter amix has an unconnected output
2.
E/FFmpeg_EpMedia: Output with label 'aout' does not exist in any defined filter graph, or was already used elsewhere.

**Comment by csuZipple** [comment]
经过长时间的调试，确定当只执行这个music方法一次时有效。再次使用这个music方法的时候就会出现上述问题，可能是资源未能及时释放导致的？期待作者的回复！

**Comment by yangjie10930** [comment]
@csuZipple 你好，经过我的研究，我认为可能是因为你第二次调用时没有更换输出文件的名称导致输入文件和输出文件同名，无法覆盖，你可以调用一次以后把输出名称换一个试试。

**Comment by csuZipple** [comment]
谢谢你的回复。
我的解决办法是在onSuccess方法里递归调用添加背景音的方法，效果还不错。
