### ISSUE TITLE
您好，咨询下该库支持Audio混音吗？

### ISSUE THREAD

**Issue by payneHwang** [yangjie10930/EpMedia#129]
通过录音获取人声获得mp3文件，然后将录音mp3文件混合背景音乐（MP3格式）形成一个新的音频文件，然后混音到原生视频中（混音可以实现将原生音频的声音音轨设置成0，而不用音视频分离的形式可以吗？），希望得到大神的帮助解答。。。

**Comment by yangjie10930** [comment]
EpEdiot.music方法

**Comment by payneHwang** [comment]
好的 感谢感谢，，，api里面好像没有调用的示例

**Comment by payneHwang** [comment]
好的看到了，谢谢，这个只能是等时长的音频文件和视频文件之间的混音吗？  
类似于电影配音功能，可以指定时间段（比如起始点0秒--3秒）进行混音吗？
大神有什么好的思路可以分享下吗？谢谢————
