### ISSUE TITLE
合成背景音超时

### ISSUE THREAD

**Issue by HiJohn** [yangjie10930/EpMedia#178]
进度大概到百分之八十多就不动了
没有日志输出
是否可以加一个超时回调
或者取消的方法

**Comment by HiJohn** [comment]
日志：
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia:   Metadata:
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia:     major_brand     : 
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia: isom
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia:     minor_version   : 
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia: 512
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia:     compatible_brands: 
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia: isomiso2avc1mp41
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia:     encoder         : 
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia: Lavf57.71.100
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia:     Stream #0:0
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia: : Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, fltp, 128 kb/s
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia:  (default)
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia:     Metadata:
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia:       encoder         : 
day 16:27:29.247 11591-12242/v I/FFmpeg_EpMedia: Lavc57.89.100 aac
day 16:27:29.248 11591-12242/v I/FFmpeg_EpMedia:     Stream #0:1
day 16:27:29.248 11591-12242/v I/FFmpeg_EpMedia: (und)
day 16:27:29.248 11591-12242/v I/FFmpeg_EpMedia: : Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 368x654 [SAR 2943:2944 DAR 9:16], q=2-31, 4053 kb/s
day 16:27:29.248 11591-12242/v I/FFmpeg_EpMedia: , 
day 16:27:29.248 11591-12242/v I/FFmpeg_EpMedia: 29.97 fps, 
day 16:27:29.248 11591-12242/v I/FFmpeg_EpMedia: 29.97 tbr, 
day 16:27:29.248 11591-12242/v I/FFmpeg_EpMedia: 30k tbn, 
day 16:27:29.248 11591-12242/v I/FFmpeg_EpMedia: 30k tbc
day 16:27:29.248 11591-12242/v I/FFmpeg_EpMedia:  (default)
day 16:27:29.248 11591-12242/v I/FFmpeg_EpMedia:     Metadata:
day 16:27:29.248 11591-12242/v I/FFmpeg_EpMedia:       handler_name    : 
day 16:27:29.248 11591-12242/v I/FFmpeg_EpMedia: VideoHandler
day 16:27:29.737 11591-12242/v I/FFmpeg_EpMedia: frame=   31 fps=0.0 q=-1.0 size=     629kB time=00:00:00.93 bitrate=5511.0kbits/s speed=1.86x    
day 16:27:30.240 11591-12242/v I/FFmpeg_EpMedia: frame=   67 fps= 67 q=-1.0 size=    1157kB time=00:00:02.13 bitrate=4438.4kbits/s speed=2.13x    
day 16:27:30.749 11591-12242/v I/FFmpeg_EpMedia: frame=  105 fps= 69 q=-1.0 size=    1804kB time=00:00:03.40 bitrate=4341.0kbits/s speed=2.25x    
day 16:27:31.250 11591-12242/v I/FFmpeg_EpMedia: frame=  142 fps= 70 q=-1.0 size=    2492kB time=00:00:04.63 bitrate=4401.1kbits/s speed= 2.3x    
day 16:27:31.756 11591-12242/v I/FFmpeg_EpMedia: frame=  173 fps= 69 q=-1.0 size=    3011kB time=00:00:05.67 bitrate=4349.0kbits/s speed=2.25x    
day 16:27:32.271 11591-12242/v I/FFmpeg_EpMedia: frame=  211 fps= 70 q=-1.0 size=    3597kB time=00:00:06.94 bitrate=4245.9kbits/s speed=2.29x    
day 16:27:32.777 11591-12242/v I/FFmpeg_EpMedia: frame=  240 fps= 68 q=-1.0 size=    4134kB time=00:00:07.90 bitrate=4282.2kbits/s speed=2.23x    
day 16:27:33.283 11591-12242/v I/FFmpeg_EpMedia: frame=  273 fps= 67 q=-1.0 size=    4676kB time=00:00:09.00 bitrate=4251.8kbits/s speed=2.23x

**Comment by HiJohn** [comment]
解决了
命令中加入
-c:a  libmp3lame

**Comment by gdoudeng** [comment]
我发现要是原本的视频有背景音乐才会卡住 老哥 有具体代码贴出来吗 我安卓小白 谢谢了 @HiJohn
