### ISSUE TITLE
如果输入文件名有空格应该怎么办？

### ISSUE THREAD

**Issue by xiaowu4** [yangjie10930/EpMedia#23]
您好，请问输入文件名有空格时应该怎么处理？比如下面这个命令
ffmpeg -y -ss 0.0 -t 60.0 -i "/storage/emulated/0/test mpeg4.mp4" -r 30 -g 30 /storage/emulated/0/out.mp4

尝试将用空格分割字符串的逻辑改了，并且为输入有空格的文件加了引号，但是仍然报文件找不到
"/storage/emulated/0/test mpeg4.mp4": No such file or directory

**Comment by yangjie10930** [comment]
FFmpegCmd.exec(String[] cmds, long duration, OnEditorListener listener) 方法，把命令拆成String数组传入

**Comment by xiaowu4** [comment]
感谢

**Comment by Limy1992** [comment]
我编辑音乐路径， 带有空格的路径，  /name - song.mp3       编辑失败ret=1

**Comment by yangjie10930** [comment]
@xiaowu4 @Limy1992 更新到最新版本，名字带空格的问题已解决。
