### ISSUE TITLE
老哥，EpEditor.exec(e, o, this);这一块会导致内存泄漏

### ISSUE THREAD

**Issue by yudengwei** [yangjie10930/EpMedia#240]
FFmpegCmd.listener = listener;
这一行代码导致FFmpegCmd持有当前activity引用，怎么解决

**Comment by yangjie10930** [comment]
用application的

**Comment by yudengwei** [comment]
这个我目前的解决办法是用反射，把这个监听器设为null。。。。还有一个问题，就是我旋转一个很短时间的视频都要花大概四五秒的时间。。这是为什么呢？感激不尽------------------ 原始邮件 ------------------
发件人: "Yang"<notifications@github.com>
发送时间: 2020年4月22日(星期三) 上午10:44
收件人: "yangjie10930/EpMedia"<EpMedia@noreply.github.com>;
抄送: "yudengwei"<906071750@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yangjie10930/EpMedia] 老哥，EpEditor.exec(e, o, this);这一块会导致内存泄漏 (#240)




 
用application的
 
&mdash;

**Comment by yangjie10930** [comment]
是的，你这个办法可以，我在最新的代码里已经置为null了
