### ISSUE TITLE
v0.9.3 -> 1.01 版本 

### ISSUE THREAD

**Issue by qingmengbanxia** [yangjie10930/EpMedia#247]
epVideo.addText(10,10,35,"red",ttfPath,text)老可以用，新版本用不了
epVideo.addText(new EpText(10,10,35,"red",ttfPath,text,new EpText.Time(3,5))) 1.01 版本 还是私有的

**Comment by yangjie10930** [comment]
是的，新版本中暂时关闭了这个方法，在更新文档里有说明，如果需要的话还是用0.9.5版本
