### ISSUE TITLE
视频加速

### ISSUE THREAD

**Issue by gaoxueying** [yangjie10930/EpMedia#25]
我使用您自定义命令，调用ffmpeg -i input.mkv -filter:v "setpts=0.5*PTS" output.mkv，将视频的速度提高一倍，失败，能帮忙看下是什么原因么

**Comment by yangjie10930** [comment]
不支持mkv格式

**Comment by gaoxueying** [comment]
嗯，谢谢你的回答，我改成以下命令是可以的：
String[] complexCommand = {"ffmpeg","-y" ,"-i", videoin,"-strict","experimental", "-filter_complex", "[0:v]setpts=0.5*PTS[v];[0:a]atempo=2.0[a]","-map","[v]","-map","[a]", "-b", "2097k","-r","60", "-vcodec", "mpeg4", videoout};

**Comment by gaoxueying** [comment]
你好，还想请教一个问题，要用自定义命令把wav的音频转acc格式的要怎么写呢

**Comment by z920792433** [comment]
String[] complexCommand = {"ffmpeg","-y" ,"-i", videoin,"-strict","experimental", "-filter_complex", "[0:v]setpts=0.5*PTS[v];[0:a]atempo=2.0[a]","-map","[v]","-map","[a]", "-b", "2097k","-r","60", "-vcodec", "mpeg4", videoout};     我用这个命令处理视频 要花好长时间才能成功哦

**Comment by bigtotorouk** [comment]
String cmd = String.format("-i %s -vf 'setpts=0.5*PTS' %s", in, out); 这个命令提示失败。。。。。 我处理的视频都是mp4格式

**Comment by yangjie10930** [comment]
@z920792433 最后加上“-preset superfast”

**Comment by yangjie10930** [comment]
@bigtotorouk 用“-filter_complex [0:v]setpts=0.5*PTS[v];[0:a]atempo=2.0[a] -map [v] -map [a]”

**Comment by bigtotorouk** [comment]
@yangjie10930  不错，速度快了很多。 还有一个小瑕疵，进度获取不到。调试发现，只有在最后成功的时候，onProgress才会被调用

**Comment by yangjie10930** [comment]
@bigtotorouk 把视频长度传进去，第二个参数
