### ISSUE TITLE
能将一堆连续拍摄的照片合并成MP4文件么？

### ISSUE THREAD

**Issue by maxdylan** [yangjie10930/EpMedia#27]
如题，谢谢

**Comment by yangjie10930** [comment]
这个功能没有封装，但是可以用自定义命令实现，例如:"ffmpeg -f image2 -i /images/%d.jpg -vcodec libx264 -r 25 -b 200k test.mp4",-r 25 表示每秒播放25帧,-b 200k 指定码率为200k

**Comment by maxdylan** [comment]
多谢多谢

**Comment by z920792433** [comment]
/images/%d.jpg    这个指定图片的路径不能是绝对路径么？ 我执行就失败

**Comment by z920792433** [comment]
我把命令改成如下就可以成功了！
-f image2 -r 0.5 -i /images/%d.jpg -vcodec mpeg4 test.mp4"
