### ISSUE TITLE
添加本地背景音乐报错

### ISSUE THREAD

**Issue by mixin716** [yangjie10930/EpMedia#29]
java.lang.IllegalStateException
 at android.media.MediaExtractor.getTrackCount(Native Method)
 at Jni.TrackUtils.selectVideoTrack(TrackUtils.java:21)
 at VideoHandle.EpEditor.music(EpEditor.java:284)
这个是什么问题啊

**Comment by yangjie10930** [comment]
参数传错了吧，是不是视频地址不对，或者视频地址的参数传入了音频地址

**Comment by mixin716** [comment]
没有啊，我是本地的mp4和aac合成

**Comment by yangjie10930** [comment]
这个错一般是地址传错了，extractor.getTrackCount()方法取不到Track引起的，你把完整的代码贴一下。

**Comment by mixin716** [comment]
EpEditor epEditor = new EpEditor(this);
String videoPath = Environment.getExternalStorageDirectory().getPath()+"/ScreenRecord/video.mp4";
String audioPath = Environment.getExternalStorageDirectory().getPath()+"/ScreenRecord/record";
String outPath = Environment.getExternalStorageDirectory().getPath()+"/ScreenRecord/handle";
epEditor.music(videoPath, audioPath, outPath, 1, 1, new OnEditorListener() {
这个是我合并的代码，audio和video的文件是存在的

**Comment by yangjie10930** [comment]
String audioPath = Environment.getExternalStorageDirectory().getPath()+"/ScreenRecord/record";
String outPath = Environment.getExternalStorageDirectory().getPath()+"/ScreenRecord/handle";
后缀？

**Comment by mixin716** [comment]
我默认就是没后缀的，不过我尝试过添加后缀，但是不起作用

**Comment by yangjie10930** [comment]
你把视频和音频发到我邮箱里我看看

**Comment by mixin716** [comment]
邮件发你了，麻烦帮忙看下，方便加个QQ或微信的请教下吗

**Comment by mendax92** [comment]
我将avi 转mp4 格式之后再进行添加背景音乐也出现这个问题
ffmpeg  -i  input.avi  -q  1  -c  copy output.mp4
还是因为编码的原因么 ？
