### ISSUE TITLE
楼主,您使用的FFmpeg版本是多少 有经过编译优化吗

### ISSUE THREAD

**Issue by cg110902** [yangjie10930/EpMedia#3]

**Comment by yangjie10930** [comment]
版本是3.2,精简和加速过。

**Comment by gzgang** [comment]
@yangjie10930  请问楼主ffmpeg精简和加速是怎么做的呢，能否提供下您的编译脚本，我编译出来的有 15M，太大了。

**Comment by yangjie10930** [comment]
把一些不需要的解码器去了，fliter也去了，留下需要的，neon加速就可以
----- 原始邮件 -----
发件人：gzgang <notifications@github.com>
收件人：yangjie10930/EpMedia <EpMedia@noreply.github.com>
抄送人：Yang <yangjie10930@sina.cn>,  Mention <mention@noreply.github.com>
主题：Re:_[yangjie10930/EpMedia]_楼主,您使用的FFmpeg版本是多少_有经过编译优化吗_(#3)
日期：2017年07月03日 23点42分

@yangjie10930  请问楼主ffmpeg精简和加速是怎么做的呢，能否提供下您的编译脚本，我编译出来的有 15M，太大了。

&mdash;

**Comment by gzgang** [comment]
@yangjie10930  非常感谢，按你的指导思路，精简了不少：）

**Comment by cg110902** [comment]
楼主 我想用您的so 文件 来做一些其它的的处理 如倒放 变速等 .您有保留这些功能吗?谢谢!
