### ISSUE TITLE
合并视频（merge）是会自动压缩视频么？

### ISSUE THREAD

**Issue by maxdylan** [yangjie10930/EpMedia#30]
我有两个40M左右的视频进行合并，合并完成的视频是2M左右，这个是会自动压缩么？用的就是merge（）方法

**Comment by yangjie10930** [comment]
会

**Comment by maxdylan** [comment]
压缩是怎么压的咧？参数可设置么？

**Comment by microshow** [comment]
@maxdylan @yangjie10930   有试过用一个无音频的视频和一个有音频的视频进行合并，最终合好的视频都没有声音了？

**Comment by yangjie10930** [comment]
@microshow 有音频和无音频的视频合并会去掉音频，还在研究怎么处理，等后续版本更新O(∩_∩)O
