### ISSUE TITLE
EpMedia混淆问题

### ISSUE THREAD

**Issue by loveJYQ** [yangjie10930/EpMedia#38]
大神，我用debug打包出来的APK运行剪辑没问题，但是用release打包出来的APK运行剪辑闪退!大佬求解答...

**Comment by yangjie10930** [comment]
混淆加上：
-keepclasseswithmembernames class * {
    native <exec>;
}

**Comment by loveJYQ** [comment]
![awuy a6 yaqrc3v3d r 9f](https://user-images.githubusercontent.com/22961321/33813593-babcaade-de5f-11e7-9d7f-73d9ce4a2acd.png)
加了之后打包出错了...

**Comment by loveJYQ** [comment]
加了之后还是报java.lang.NoSuchMethodError: no static method "LJni/FFmpegCmd;.onProgress(F)V"

**Comment by yangjie10930** [comment]
我这边粘贴的时候被屏蔽了一部分= =
<methods>加在native后面

**Comment by lll-01** [comment]
....我也是被这个坑了... , 而且包名也太短了吧... jni , VideoHandle , 都不再一个包下 , 这个最好能改一下 , 
而且建议关键方法上加上 @Keep 注解 

```
package VideoHandle;

public interface OnEditorListener {
    void onSuccess();

    void onFailure();

    void onProgress(float var1);
}

```

这个不能被混淆 , 然后他也不是 native 方法

**Comment by lichtz** [comment]
-keep class  com.joe.joevideolib.**{*;}
-keep class Jni.**{*;}
-keep class VideoHandle.**{*;}

**Comment by loveJYQ** [comment]
楼上方法有效
