### ISSUE TITLE
楼主,您使用的FFmpeg能处理其它格式的视频吗，如video.ts格式的?

### ISSUE THREAD

**Issue by Yogurtla** [yangjie10930/EpMedia#4]
因为我解析video.ts格式的视频时报错了：
07-05 15:06:39.120 6453-6541/com.kugou.myapplication E/FFmpeg_VideoTest: /storage/emulated/0/HAISHI/COMMONMOVIE/test.ts: Invalid data found when processing input
想知道有什么处理方案，ffmpeg支不支持

**Comment by yangjie10930** [comment]
抱歉，编译的时候并没有添加对ts的支持。

**Comment by wm0124** [comment]
大华摄像头录制  ，有时可以转码，有时会提示 FFmpeg_EpMedia: /storage/emulated/0/DCIM/Movie/1586858958_1.dav: Invalid data found when processing input
