### ISSUE TITLE
您好，可否在EpEditor这个类增加 destroy 方法

### ISSUE THREAD

**Issue by falll2000** [yangjie10930/EpMedia#40]
您好

感谢您开发这麼好用的工具
最近使用这个专案合併 video 的时候，发现传进EpEditor的 context 对象
会导致 memory leak

是否能在EpEditor 内增加 destroy 方法将 context 对象清掉呢

谢谢

**Comment by yangjie10930** [comment]
您好，感谢您的建议，我会在接下来的版本中改进O(∩_∩)O，再次谢谢您

**Comment by Vashon** [comment]
作者传context到EpEditor主要是用于将回调切换到主线程中执行，我觉得可以写一个HandlerUtils类来完成这个工作，这样在实例化EpEditor时就可以不用传context，也就不会有内存泄漏的问题了。
`public class HandlerUtils {
    
    private HandlerUtils() {
    }

    public static Handler getMainHandler() {
        return new Handler(Looper.getMainLooper());
    }

    public static void postOnMain(Runnable message) {
        getMainHandler().post(message);
    }

    public static void postOnMainWithDelay(Runnable message, long delayMillis) {
        getMainHandler().postDelayed(message, delayMillis);
    }
}`
