### ISSUE TITLE
视频访问不了

### ISSUE THREAD

**Issue by Corusaki** [yangjie10930/EpMedia#49]
自己录制的视频 地址传进去 报错Decoder (codec amr_nb) not found for input stream #0:1
是为什么啊

**Comment by yangjie10930** [comment]
什么格式，3GPP的不支持。

**Comment by Corusaki** [comment]
@yangjie10930 我去换个格式 我用的amr_nb。。 谢谢！

**Comment by Corusaki** [comment]
@yangjie10930  谢谢 就是音频格式问题 ！解决了 谢谢

**Comment by yangjie10930** [comment]
@Corusaki 不客气^_^
