### ISSUE TITLE
视频MP4不能合成MP3格式的音频吗?

### ISSUE THREAD

**Issue by o03150** [yangjie10930/EpMedia#51]
V/EpMediaF: cmd:ffmpeg
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:-y
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:-i
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:/storage/emulated/0/1516097413668_video.mp4
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:-i
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:/storage/emulated/0/audio.mp3
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:-filter_complex
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:[0:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,volume=1.0[a0];[1:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,volume=0.7[a1];[a0][a1]amix=inputs=2:duration=first[aout]
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:-map
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:[aout]
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:-ac
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:2
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:-c:v
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:copy
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:-map
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:0:v:0
01-16 18:10:29.641 12239-12239/com.wuxianzixun.mapex V/EpMediaF: cmd:/storage/emulated/0/1516097428971_video_edit.mp4\

报以下错误:
E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
E/FFmpeg_EpMedia: Failed to read frame size: Could not seek to 1026.
E/FFmpeg_EpMedia: /storage/emulated/0/audio.mp3: Invalid argument

怎么肥四?

**Comment by yangjie10930** [comment]
可以的，mp3确定格式没错？

**Comment by o03150** [comment]
你说对了- -!我把raw中的MP3以流形式写出到文件,虽然以.MP3格式命名,本地播放器也可以播放,但是并没有封装MP3其他标识信息,导致ffmpeg识别不了

不知道有什么方法可以解决,大神

**Comment by yangjie10930** [comment]
使用lamemp3这个库把pcm数据封装成mp3，我发现好多人有这个问题，在后续版本中我把pcm加进去吧

**Comment by o03150** [comment]
嗯嗯,十分感谢
