### ISSUE TITLE
多个添加了不同滤镜的视频 ，合成后有问题 但是在合成的过程中并没有报错 

### ISSUE THREAD

**Issue by z920792433** [yangjie10930/EpMedia#57]
这个滤镜是我在拍摄视频的过程中加上的
合成后的视频只能播放一段 后面的播放不了 （用的是无损多视频合并）
请问为什么会出现这种情况呢？

**Comment by z920792433** [comment]
EpEditor.merge（...） 我用了这个方法合成就没有问题 但是时间就稍微久点！！

**Comment by z920792433** [comment]
EpEditor.merge（...）我用这个方法 时间久的超出了可接受范围啊   请问有什么办法加快一下速度么

**Comment by yangjie10930** [comment]
再快用这个框架已经不大可能了，你可以试试硬编解码+OpenGl

**Comment by z920792433** [comment]
好吧 谢谢亲~
