### ISSUE TITLE
文字添加失败

### ISSUE THREAD

**Issue by xulingchung2016** [yangjie10930/EpMedia#58]
楼主，你好，我想给视频添加水印，回调onFailure接口，不知哪里的问题？代码如下：

  EpVideo epVideo = new EpVideo(filepaht);
//        epVideo.clip(5,10);
//            epVideo.crop(480,360,0,0);
            epVideo.addText(10,10,35,"red","/storage/sdcard1/wtlive/temp/Torcing.ttf","123456");
//            EpText epText = new EpText(0, 20, 35, EpText.Color.Red, null, "单独打开看看可开嘉来", );
//            epVideo.addText(epText);
//            EpEditor epEditor = new EpEditor(this);
            //输出选项，参数为输出文件路径(目前仅支持mp4格式输出)
            EpEditor.OutputOption outputOption = new EpEditor.OutputOption(workingPath + "/real4.mp4");
            EpEditor.exec(epVideo, outputOption, new OnEditorListener() {
                @Override
                public void onSuccess() {

                }

                @Override
                public void onFailure() {
                    android.util.Log.d("progress", "progress:fail");
                }

                @Override
                public void onProgress(float progress) {
                    //这里获取处理进度
                    android.util.Log.d("progress", "progress:" + progress);
              /*  if(progress==1.0f){
                    videosToMerge = new ArrayList<>();
                    videosToMerge.add(workingPath+"/real4.mp4");
                    videosToMerge.add(filepaht2);
                    outName = "test55.mp4";
                    videoMerge = new VideoMerge(workingPath,videosToMerge,outName);
                    videoMerge.merge();
                }*/
                }

**Comment by yangjie10930** [comment]
logcat发一下
