### ISSUE TITLE
你说有转码，结果我找半天没看到骗我

### ISSUE THREAD

**Issue by xiejinsorry** [yangjie10930/EpMedia#6]
同时执行execCmd("-y -i "+sourcePath+" "+targetPath,new OnEdit....)也不行

**Comment by yangjie10930** [comment]
什么格式转什么格式？
----- 原始邮件 -----
发件人：xiejinsorry <notifications@github.com>
收件人：yangjie10930/EpMedia <EpMedia@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[yangjie10930/EpMedia]_你说有转码，结果我找半天没看到骗我_(#6)
日期：2017年08月04日 11点28分

同时执行execCmd("-y -i "+sourcePath+" "+targetPath,new OnEdit....)也不行

&mdash;
