### ISSUE TITLE
请问关于视频合成的问题

### ISSUE THREAD

**Issue by ViviviVirgil** [yangjie10930/EpMedia#60]
![image](https://user-images.githubusercontent.com/33839347/36099851-166ef484-103f-11e8-9221-f6a726a4574d.png)
new EpEditor.OutputOption(outFile)里的参数是需要填File吗？

**Comment by yangjie10930** [comment]
输出文件的路径，String类型 比如xxx/xxx/out.mp4

**Comment by ViviviVirgil** [comment]
EpEditor.mergeByLc(epVideos, new EpEditor.OutputOption(Environment.getExternalStorageDirectory().getAbsolutePath()+"/aaaa.mp4"), new OnEditorListener() {
            @Override
            public void onSuccess() {

            }

            @Override
            public void onFailure() {

            }

            @Override
            public void onProgress(float progress) {
                //这里获取处理进度
            }
        });
我改成这个代码之后这个方法中mergeByLc后面的全报错，这是怎么回事

**Comment by yangjie10930** [comment]
logcat

**Comment by ViviviVirgil** [comment]
Error:(55, 17) 错误: 无法将类 EpEditor中的方法 mergeByLc应用到给定类型;
需要: Context,List<EpVideo>,OutputOption,OnEditorListener
找到: ArrayList<EpVideo>,OutputOption,<匿名OnEditorListener>
原因: 实际参数列表和形式参数列表长度不同

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
