### ISSUE TITLE
加减速之后，视频会花

### ISSUE THREAD

**Issue by bigtotorouk** [yangjie10930/EpMedia#77]
changePTS之后，视频会花。。。

**Comment by yangjie10930** [comment]
参数是多少，贴一下

**Comment by bigtotorouk** [comment]
@yangjie10930  测试发现，单独加减速一个视频是没问题。 出现花的问题是：多个视频，其中一个视频加减速处理，然后这么多视频合成，然后就花了。

**Comment by bigtotorouk** [comment]
![image](https://user-images.githubusercontent.com/1658469/37394135-11db32de-2741-11e8-9c0c-854cea8bac30.png)
![image](https://user-images.githubusercontent.com/1658469/37394175-3030b754-2741-11e8-8ee9-b0d709ab7d22.png)
