### ISSUE TITLE
您好，请问在处理的过程中怎么显示进度啊

### ISSUE THREAD

**Issue by xiaowu4** [yangjie10930/EpMedia#8]
如果处理时间较长，希望实时显示进度怎么办呢？

**Comment by yangjie10930** [comment]
你好，现在版本暂时没法获取处理进度，后续版本我会添加进度的回调接口，敬请关注。

**Comment by xiaowu4** [comment]
我如果想要截取图片，使用该库也是无法实现的吗？结果显示找不到相应的输出格式，Unable to find a suitable output format

**Comment by xiaowu4** [comment]
@yangjie10930 我如果想要截取图片，使用该库也是无法实现的吗？结果显示找不到相应的输出格式，Unable to find a suitable output format

**Comment by yangjie10930** [comment]
@xiaowu4 能贴下你的命令吗，截取图片可以实现的，Unable to find a suitable output format错误检查下你的命令间是否有多余空格。

**Comment by xiaowu4** [comment]
@yangjie10930 String cmd = "-i " + inputPath + " -r 1 /storage/emulated/0/QQBrowser/视频/out%d.jpeg";
我看了看好像没有多余的空格，我现在的需求是隔1s截一帧。-r 1 就是隔一秒截一次
输出显示的是
Unable to find a suitable output format for '/storage/emulated/0/QQBrowser/视频/out%d.jpeg'
/storage/emulated/0/QQBrowser/视频/out%d.jpeg: Invalid argument

**Comment by yangjie10930** [comment]
@xiaowu4 好的，已发现问题，近日内我会发布下个版本，会修复这个问题，也会添加处理的进度，谢谢你的关注。

**Comment by xiaowu4** [comment]
@yangjie10930 感谢

**Comment by yangjie10930** [comment]
@xiaowu4  已新增处理进度，更新至最新版，在回调函数中新增了onProgress方法，可获取处理进度。

**Comment by xiaowu4** [comment]
@yangjie10930 收到，感谢

**Comment by xiaowu4** [comment]
@yangjie10930 我试了一下进度可以了，那截图的可以吗？我这边还是有问题

**Comment by xiaowu4** [comment]
@yangjie10930  ffmpeg 命令中带有 “-loop 1”时好像进度没有变化，是怎么回事吗
