### ISSUE TITLE
如何缩短多个视频合并的时间.

### ISSUE THREAD

**Issue by z920792433** [yangjie10930/EpMedia#9]
我合成 两段视频 总共30秒 合成的时间花了5分钟

**Comment by yangjie10930** [comment]
如果两个视频格式分辨率这些相同，可以尝试使用无损压缩的方法，时间会大大缩短。

**Comment by z920792433** [comment]
恩 我试过了 但是分辨率不一样合成的速度就非常慢 
不过还是谢谢亲啦 帮我大忙
