### ISSUE TITLE
Ffmpeg is slow

### ISSUE THREAD

**Issue by amitsharma492** [yangjie10930/EpMedia#99]
I am trying to Apply Blurbox filter using following 

[0:v]scale=ih*16/9:-1,boxblur=luma_radius=min(h\,w)/20:luma_power=1:chroma_radius=min(cw\,ch)/20:chroma_power=1[bg];[bg][0:v]overlay=(W-w)/2:(H-h)/2,crop=h=iw*9/16

but this Execution Speed is slow. Can be achieve better speed? Thanks for this Lib.

**Comment by yangjie10930** [comment]
You can try using OpenGl, in FragmentShader, when the samples are read from the image, the migration of the texture coordinates is carried out, and the four samples of the upper left and the right bottom are extracted from the image, and then the average value is taken in the shaders.

**Comment by yangjie10930** [comment]
You can try command  '-preset superfast', EpMedia is free.

**Comment by amitsharma492** [comment]
how to use -preset superfast along with epVideo.draw

**Comment by amitsharma492** [comment]
I don't know much about OpenGl, any suggestions?

**Comment by yangjie10930** [comment]
@amitsharma492 https://github.com/yangjie10930/OpenGL4Android

**Comment by amitsharma492** [comment]
Thanks @yangjie10930.
How can loop the background music while mux with Video ?
like Video Duration is  - 2 mins
Audio - 20sec
using EpEditor.music I am not able to loop the background music.

**Comment by aliraza96** [comment]
> Thanks @yangjie10930.
> How can loop the background music while mux with Video ?
> like Video Duration is - 2 mins
> Audio - 20sec
> using EpEditor.music I am not able to loop the background music.

Did you find a fix for this bro ?

**Comment by knowamit** [comment]
@aliraza96

Yes I have solved this issue by using simple two steps 

1.  Calculate how many times I have to loop the audio as compare to video. 

2.  Loop the audio using the "merge" method 

3. Add final audio to video
